### ISSUE TITLE
Tutorial links need to be updated

### ISSUE THREAD

**Issue by adressel** [VowpalWabbit/vowpalwabbit.github.io#117]
Hi,

I noticed that the tutorial links at the top of this page need to be updated: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Tutorial

The links point to https://vowpalwabbit.org/guides/, but the correct address appears to be https://vowpalwabbit.org/tutorials/, for example https://vowpalwabbit.org/tutorials/getting_started.html.

Thanks!

**Comment by cheng-tan** [comment]
Thanks for the feedback. Links have been updated. Closing this issue.
