### ISSUE TITLE
Typos / missing spacing in Figure

### ISSUE THREAD

**Issue by sebastianbertoli** [VowpalWabbit/vowpalwabbit.github.io#152]
### Description

Typo and missing space in text.

exhist -> exist

Spacing before/after bold A.

### Link 

https://vowpalwabbit.org/assets/images/feature_details/reduction_stack.jpg

**Comment by nessamilan** [comment]
@cheng-tan @jackgerrits Fixed graphic attached below:

![reduction_stack](https://user-images.githubusercontent.com/6819397/110362288-f5a6da80-7ff5-11eb-9844-bd10c85984f8.png)
