### ISSUE TITLE
Add relevant <meta> tags to header

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/vowpalwabbit.github.io#26]
https://gist.github.com/MicBrain/46a9723158307fd30db66a4b2af85411#gistcomment-2750974

**Comment by cheng-tan** [comment]
@mikedropmedia  we need to add meta description for following pages:
- [ ] homepage
- [ ] get started page
- [ ] research
- [ ] tutorials

Also need to add search engine keywords for the website.
