### ISSUE TITLE
CB tutorial

### ISSUE THREAD

**Issue by cheng-tan** [VowpalWabbit/vowpalwabbit.github.io#4]
Create a CB tutorial with python.

Here's a link to it: https://github.com/cheng-tan/vowpalwabbit.github.io/blob/master/_guides/contextual_bandits.md

**Comment by kumpera** [comment]
Pavithra is working on it.

**Comment by pavithraks** [comment]
https://cheng-tan.github.io/vowpalwabbit.github.io/guides/contextual_bandits.html 

It's already up there. Do I need to do anything else?

**Comment by pavithraks** [comment]
It's merged and on the site. People can make edits by submitting pull requests. So, I'm going to mark this as closed.

**Comment by kumpera** [comment]
Doc is merged and now ready to be copy&edited

**Comment by cheng-tan** [comment]
PR #14
